const data = [
    {
        id: 0,
        name: "Test Name",
        status: 1,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 1,
        name: "Dementiy",
        status: 2,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 2,
        name: "Amogus",
        status: 3,
        comment: "Test Comment Test Comment Test Comment Test Comment",
        address: "Saint Petersburg",
    },
    {
        id: 3,
        name: "Test Name",
        status: 1,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 4,
        name: "Dementiy",
        status: 2,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 5,
        name: "Amogus",
        status: 3,
        comment: "Test Comment Test Comment Test Comment Test Comment",
        address: "Saint Petersburg",
    },
    {
        id: 6,
        name: "Test Name",
        status: 1,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 7,
        name: "Dementiy",
        status: 2,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 8,
        name: "Amogus",
        status: 3,
        comment: "Test Comment Test Comment Test Comment Test Comment",
        address: "Saint Petersburg",
    },
    {
        id: 9,
        name: "Test Name",
        status: 1,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 10,
        name: "Dementiy",
        status: 2,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 11,
        name: "Amogus",
        status: 3,
        comment: "Test Comment Test Comment Test Comment Test Comment",
        address: "Saint Petersburg",
    },
    {
        id: 12,
        name: "Test Name",
        status: 1,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 13,
        name: "Dementiy",
        status: 2,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 14,
        name: "Amogus",
        status: 3,
        comment: "Test Comment Test Comment Test Comment Test Comment",
        address: "Saint Petersburg",
    },
    {
        id: 15,
        name: "Test Name",
        status: 1,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 16,
        name: "Dementiy",
        status: 2,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 17,
        name: "Amogus",
        status: 3,
        comment: "Test Comment Test Comment Test Comment Test Comment",
        address: "Saint Petersburg",
    },
    {
        id: 18,
        name: "Test Name",
        status: 1,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 19,
        name: "Dementiy",
        status: 2,
        comment: "Test Comment",
        address: "Moscow",
    },
    {
        id: 20,
        name: "Amogus",
        status: 3,
        comment: "Test Comment Test Comment Test Comment Test Comment",
        address: "Saint Petersburg",
    },
]

export default data